databases:
  - name: langgraph-postgres # Render PG16
    databaseName: private
    postgresMajorVersion: "16"


services:
  - type: redis # Render Redis
    name: langgraph-redis
    ipAllowList: []

  - type: web
    name: langgraph-api
    runtime: docker
    envVars:
      - key: PORT
        value: 8000
      - key: REDIS_URI
        fromService:
          type: redis
          name: langgraph-redis
          property: connectionString
      - key: POSTGRES_URI
        fromDatabase:
          name: langgraph-postgres
          property: connectionString
    disk:
      name: langgraph-data
      mountPath: /
  
